### PR TITLE
Make react peerDependency instead of dependency

### PR DESCRIPTION
**Pull request by davesnx**

### CODE REVIEW

**Comment by danieleleoni** [comment]
Hi @davesnx! Thanks for contributing to this project.
Can you provide additional information about this PR? Why do you want to set React as peer dependency?

**Comment by davesnx** [comment]
Sorry for the non-description PR.

`peerDependency` means that the Application where you use the module must have the dependency to have it running, but you don't want it on the bundle. 

It's a dependency that the system must have aswell as a dependency.

right now:
```
App 
- node_modules
-- react
-- new-relic-react
--- node_modules
---- react
```

after this PR:
```
App
- node_modules
-- react
-- new-relic-react
```

More info about `peerDependency` from [nodejs/blog](https://nodejs.org/en/blog/npm/peer-dependencies/) or [npm docs](https://docs.npmjs.com/files/package.json#peerdependencies)

**Comment by davesnx** [comment]
Any advance on that?

**Comment by santimendoza** [comment]
@davesnx The package will be smaller, more fast to install and the node_modules will be smaller too.

**Comment by santimendoza** [comment]
@davesnx Did you solve this already (in another PR)? Or you think this is not necessary?

**Comment by davesnx** [comment]
I didn't fix the problem in this lib, I just fork it internally in my org. 

After 2 year of a PR open and no maintanance of this project I just close this PR.

**Pull request closed without merging**
